import type { Item, Customer, Transaction, StocktakingSession } from "@/types";

const today = new Date();
const yesterday = new Date(today.getTime() - 86400000);
const twoDaysAgo = new Date(today.getTime() - 86400000 * 2);
const threeDaysAgo = new Date(today.getTime() - 86400000 * 3);
const weekAgo = new Date(today.getTime() - 86400000 * 7);

export const SAMPLE_CUSTOMERS: Customer[] = [
  {
    id: "c1",
    lastName: "田中",
    firstName: "太郎",
    lastNameKana: "タナカ",
    firstNameKana: "タロウ",
    phone: "090-1234-5678",
    address: "東京都渋谷区神宮前1-2-3",
    identityVerified: true,
    identityDocumentType: "drivers_license",
    identityVerifiedAt: weekAgo,
    customerType: "both",
    totalSellCount: 3,
    totalBuyCount: 2,
    totalSellAmount: 15000,
    totalBuyAmount: 8500,
    note: "常連のお客様。ストリート系が好み。",
    createdAt: weekAgo,
    updatedAt: yesterday,
  },
  {
    id: "c2",
    lastName: "佐藤",
    firstName: "花子",
    lastNameKana: "サトウ",
    firstNameKana: "ハナコ",
    phone: "080-9876-5432",
    address: "東京都新宿区西新宿4-5-6",
    identityVerified: true,
    identityDocumentType: "my_number",
    identityVerifiedAt: threeDaysAgo,
    customerType: "seller",
    totalSellCount: 1,
    totalBuyCount: 0,
    totalSellAmount: 12000,
    totalBuyAmount: 0,
    note: "",
    createdAt: threeDaysAgo,
    updatedAt: threeDaysAgo,
  },
  {
    id: "c3",
    lastName: "鈴木",
    firstName: "一郎",
    lastNameKana: "スズキ",
    firstNameKana: "イチロウ",
    phone: "070-5555-1234",
    address: "東京都世田谷区下北沢2-8-1",
    identityVerified: false,
    identityDocumentType: "",
    identityVerifiedAt: null,
    customerType: "buyer",
    totalSellCount: 0,
    totalBuyCount: 4,
    totalSellAmount: 0,
    totalBuyAmount: 22000,
    note: "デニム好き",
    createdAt: weekAgo,
    updatedAt: twoDaysAgo,
  },
  {
    id: "c4",
    lastName: "山田",
    firstName: "美咲",
    lastNameKana: "ヤマダ",
    firstNameKana: "ミサキ",
    phone: "090-3333-7777",
    address: "東京都目黒区自由が丘1-1-1",
    identityVerified: true,
    identityDocumentType: "passport",
    identityVerifiedAt: twoDaysAgo,
    customerType: "both",
    totalSellCount: 2,
    totalBuyCount: 1,
    totalSellAmount: 8000,
    totalBuyAmount: 4500,
    note: "",
    createdAt: twoDaysAgo,
    updatedAt: yesterday,
  },
];

export const SAMPLE_ITEMS: Item[] = [
  {
    id: "i1",
    name: "Levi's 501 デニムパンツ W32",
    brand: "Levi's",
    category: "bottoms",
    subcategory: "デニム",
    size: "M",
    color: "ブルー",
    condition: "A",
    purchasePrice: 2000,
    sellingPrice: 4980,
    customerId: "c1",
    purchaseTransactionId: "t1",
    photoUrls: [],
    barcode: "HKM-20260312-0001",
    status: "in_stock",
    registeredBy: "ゲストスタッフ",
    createdAt: threeDaysAgo,
    updatedAt: threeDaysAgo,
  },
  {
    id: "i2",
    name: "THE NORTH FACE マウンテンパーカー",
    brand: "THE NORTH FACE",
    category: "outerwear",
    subcategory: "マウンテンパーカー",
    size: "L",
    color: "ブラック",
    condition: "S",
    purchasePrice: 5000,
    sellingPrice: 12800,
    customerId: "c2",
    purchaseTransactionId: "t2",
    photoUrls: [],
    barcode: "HKM-20260313-0001",
    status: "in_stock",
    registeredBy: "ゲストスタッフ",
    createdAt: twoDaysAgo,
    updatedAt: twoDaysAgo,
  },
  {
    id: "i3",
    name: "Supreme Box Logo Tシャツ",
    brand: "Supreme",
    category: "tops",
    subcategory: "Tシャツ",
    size: "M",
    color: "ホワイト",
    condition: "B",
    purchasePrice: 8000,
    sellingPrice: 15800,
    customerId: "c1",
    purchaseTransactionId: "t1",
    photoUrls: [],
    barcode: "HKM-20260312-0002",
    status: "sold",
    registeredBy: "ゲストスタッフ",
    createdAt: threeDaysAgo,
    updatedAt: yesterday,
  },
  {
    id: "i4",
    name: "Nike Air Force 1 Low White",
    brand: "Nike",
    category: "shoes",
    subcategory: "スニーカー",
    size: "L",
    color: "ホワイト",
    condition: "A",
    purchasePrice: 3000,
    sellingPrice: 6980,
    customerId: "c4",
    purchaseTransactionId: "t4",
    photoUrls: [],
    barcode: "HKM-20260314-0001",
    status: "in_stock",
    registeredBy: "ゲストスタッフ",
    createdAt: yesterday,
    updatedAt: yesterday,
  },
  {
    id: "i5",
    name: "BEAMS チェックシャツ",
    brand: "BEAMS",
    category: "tops",
    subcategory: "シャツ",
    size: "M",
    color: "レッド",
    condition: "B",
    purchasePrice: 1500,
    sellingPrice: 3480,
    customerId: "c1",
    purchaseTransactionId: "t1",
    photoUrls: [],
    barcode: "HKM-20260312-0003",
    status: "in_stock",
    registeredBy: "ゲストスタッフ",
    createdAt: threeDaysAgo,
    updatedAt: threeDaysAgo,
  },
  {
    id: "i6",
    name: "Ralph Lauren ニットセーター",
    brand: "Ralph Lauren",
    category: "tops",
    subcategory: "ニット",
    size: "L",
    color: "ネイビー",
    condition: "A",
    purchasePrice: 2500,
    sellingPrice: 5980,
    customerId: "c2",
    purchaseTransactionId: "t2",
    photoUrls: [],
    barcode: "HKM-20260313-0002",
    status: "in_stock",
    registeredBy: "ゲストスタッフ",
    createdAt: twoDaysAgo,
    updatedAt: twoDaysAgo,
  },
  {
    id: "i7",
    name: "Patagonia フリースベスト",
    brand: "Patagonia",
    category: "outerwear",
    subcategory: "ベスト",
    size: "M",
    color: "グリーン",
    condition: "B",
    purchasePrice: 3500,
    sellingPrice: 7480,
    customerId: "c4",
    purchaseTransactionId: "t4",
    photoUrls: [],
    barcode: "HKM-20260314-0002",
    status: "in_stock",
    registeredBy: "ゲストスタッフ",
    createdAt: yesterday,
    updatedAt: yesterday,
  },
  {
    id: "i8",
    name: "Dr.Martens 8ホールブーツ",
    brand: "Dr.Martens",
    category: "shoes",
    subcategory: "ブーツ",
    size: "L",
    color: "ブラック",
    condition: "C",
    purchasePrice: 4000,
    sellingPrice: 8980,
    customerId: "c1",
    purchaseTransactionId: "t5",
    photoUrls: [],
    barcode: "HKM-20260315-0001",
    status: "in_stock",
    registeredBy: "ゲストスタッフ",
    createdAt: today,
    updatedAt: today,
  },
];

export const SAMPLE_TRANSACTIONS: Transaction[] = [
  {
    id: "t1",
    type: "purchase",
    customerId: "c1",
    customerName: "田中 太郎",
    items: [
      { itemId: "i1", itemName: "Levi's 501 デニムパンツ W32", brand: "Levi's", price: 2000 },
      { itemId: "i3", itemName: "Supreme Box Logo Tシャツ", brand: "Supreme", price: 8000 },
      { itemId: "i5", itemName: "BEAMS チェックシャツ", brand: "BEAMS", price: 1500 },
    ],
    subtotal: 11500,
    total: 11500,
    paymentMethod: "cash",
    amountReceived: 0,
    change: 0,
    staffId: "guest",
    staffName: "ゲストスタッフ",
    receiptNumber: "P-20260312-0001",
    note: "",
    createdAt: threeDaysAgo,
    updatedAt: threeDaysAgo,
  },
  {
    id: "t2",
    type: "purchase",
    customerId: "c2",
    customerName: "佐藤 花子",
    items: [
      { itemId: "i2", itemName: "THE NORTH FACE マウンテンパーカー", brand: "THE NORTH FACE", price: 5000 },
      { itemId: "i6", itemName: "Ralph Lauren ニットセーター", brand: "Ralph Lauren", price: 2500 },
    ],
    subtotal: 7500,
    total: 7500,
    paymentMethod: "cash",
    amountReceived: 0,
    change: 0,
    staffId: "guest",
    staffName: "ゲストスタッフ",
    receiptNumber: "P-20260313-0001",
    note: "",
    createdAt: twoDaysAgo,
    updatedAt: twoDaysAgo,
  },
  {
    id: "t3",
    type: "sale",
    customerId: "c3",
    customerName: "鈴木 一郎",
    items: [
      { itemId: "i3", itemName: "Supreme Box Logo Tシャツ", brand: "Supreme", price: 15800 },
    ],
    subtotal: 15800,
    total: 15800,
    paymentMethod: "cash",
    amountReceived: 20000,
    change: 4200,
    staffId: "guest",
    staffName: "ゲストスタッフ",
    receiptNumber: "S-20260314-0001",
    note: "",
    createdAt: yesterday,
    updatedAt: yesterday,
  },
  {
    id: "t4",
    type: "purchase",
    customerId: "c4",
    customerName: "山田 美咲",
    items: [
      { itemId: "i4", itemName: "Nike Air Force 1 Low White", brand: "Nike", price: 3000 },
      { itemId: "i7", itemName: "Patagonia フリースベスト", brand: "Patagonia", price: 3500 },
    ],
    subtotal: 6500,
    total: 6500,
    paymentMethod: "cash",
    amountReceived: 0,
    change: 0,
    staffId: "guest",
    staffName: "ゲストスタッフ",
    receiptNumber: "P-20260314-0001",
    note: "",
    createdAt: yesterday,
    updatedAt: yesterday,
  },
  {
    id: "t5",
    type: "purchase",
    customerId: "c1",
    customerName: "田中 太郎",
    items: [
      { itemId: "i8", itemName: "Dr.Martens 8ホールブーツ", brand: "Dr.Martens", price: 4000 },
    ],
    subtotal: 4000,
    total: 4000,
    paymentMethod: "cash",
    amountReceived: 0,
    change: 0,
    staffId: "guest",
    staffName: "ゲストスタッフ",
    receiptNumber: "P-20260315-0001",
    note: "",
    createdAt: today,
    updatedAt: today,
  },
  {
    id: "t6",
    type: "sale",
    customerId: "",
    customerName: "",
    items: [
      { itemId: "i1", itemName: "Levi's 501 デニムパンツ W32", brand: "Levi's", price: 4980 },
    ],
    subtotal: 4980,
    total: 4980,
    paymentMethod: "credit_card",
    amountReceived: 0,
    change: 0,
    staffId: "guest",
    staffName: "ゲストスタッフ",
    receiptNumber: "S-20260315-0001",
    note: "",
    createdAt: today,
    updatedAt: today,
  },
];

export const SAMPLE_STOCKTAKING_SESSIONS: StocktakingSession[] = [
  {
    id: "st1",
    status: "closed",
    scope: "category",
    targetCategory: "tops",
    startedBy: "ゲストスタッフ",
    scannedItems: [
      { itemId: "i3", barcode: "HKM-20260312-0002", itemName: "Supreme Box Logo Tシャツ", brand: "Supreme", scannedAt: twoDaysAgo, scannedBy: "ゲストスタッフ" },
      { itemId: "i5", barcode: "HKM-20260312-0003", itemName: "BEAMS チェックシャツ", brand: "BEAMS", scannedAt: twoDaysAgo, scannedBy: "ゲストスタッフ" },
      { itemId: "i6", barcode: "HKM-20260313-0002", itemName: "Ralph Lauren ニットセーター", brand: "Ralph Lauren", scannedAt: twoDaysAgo, scannedBy: "ゲストスタッフ" },
    ],
    report: {
      systemCount: 3,
      scannedCount: 3,
      matchedCount: 3,
      missingItems: [],
      unknownBarcodes: [],
    },
    note: "トップスの定期棚卸",
    createdAt: twoDaysAgo,
    closedAt: twoDaysAgo,
  },
  {
    id: "st2",
    status: "open",
    scope: "full",
    targetCategory: "",
    startedBy: "ゲストスタッフ",
    scannedItems: [
      { itemId: "i1", barcode: "HKM-20260312-0001", itemName: "Levi's 501 デニムパンツ W32", brand: "Levi's", scannedAt: today, scannedBy: "ゲストスタッフ" },
      { itemId: "i2", barcode: "HKM-20260313-0001", itemName: "THE NORTH FACE マウンテンパーカー", brand: "THE NORTH FACE", scannedAt: today, scannedBy: "ゲストスタッフ" },
    ],
    report: null,
    note: "月次全品棚卸",
    createdAt: today,
    closedAt: null,
  },
];
